kind: Service
apiVersion: v1
metadata:
  name: goecho
  namespace: duck
  labels:
    app: goecho
spec:
  selector:
    app: goecho
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    name: http
  type: NodePort
